#!/bin/sh
#set -x
[ "$INTERACTIVE" = "" ] && opts="--non-interactive"
user=${1:?}
passwd=${2:?}

##
## Register password for SVN projects
##
cp ${HOME}/.subversion/config.cred ${HOME}/.subversion/config

projects="arm-compilers open64 aci ecc STxP70Valid stxp70cc FPx sde STxP70-CI-Data gbu tango/Tx bilbocc validation4cec mds svnbranch flexcc binopt aci binopt mad newlib lisa libifr MPx embedbenchmarks embednet gcc4net CLIC mobileaudio MMTE mmtools ndkenscore st200-gdb sh4gcc leda5 mmdsp-tools mmdsp-libsrc mmdspcc mmdsp-compiler sts-gdb SMEC svasoft SEA STxP70-DIVx stxp71archi VECx CRCx"
for i in $projects; do
    echo "Setting credentials of $i for $USER to real user $user"
    #
    root=//codex.cro.st.com/svnroot 
    svn ls $opts --username "$user" --password $passwd http:$root/$i >/dev/null
    svn ls $opts --username "$user" --password $passwd https:$root/$i >/dev/null
    #
    svn ls $opts --username "$user" --password $passwd http://svn.$i.codex.cro.st.com/svnroot/$i >/dev/null
    svn ls $opts --username "$user" --password $passwd https://svn.$i.codex.cro.st.com/svnroot/$i >/dev/null
done

cp ${HOME}/.subversion/config.nocred ${HOME}/.subversion/config

echo "--------"

##
## Login to Codex CLI for File Repository Access
##
cli_projects="stxp70-ci-data"
for i in $cli_projects; do
    echo "Login to Codex CLI for project $i with $USER to real user $user"
    /sw/st/gnu_compil/gnu/Linux-RH-WS-3/bin/php /sw/st/gnu_compil/comp/scripts/codendi_cli-1.4.1/codendi.php login --username="$user" --password="$passwd" --project=$i
done
